import streamlit as st
import torch
import torch.nn as nn
import numpy as np
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from fpdf import FPDF
import tempfile

# --- 1. DEFINE MODEL CLASS ---
class Autoencoder(nn.Module):
    def __init__(self, input_dim):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 20), nn.Tanh(),
            nn.Linear(20, 14), nn.Tanh(),
            nn.Linear(14, 8), nn.Tanh(),
        )
        self.decoder = nn.Sequential(
            nn.Linear(8, 14), nn.Tanh(),
            nn.Linear(14, 20), nn.Tanh(),
            nn.Linear(20, input_dim),
        )

    def forward(self, x):
        encoded = self.encoder(x)
        decoded = self.decoder(encoded)
        return decoded

# --- 2. LOAD ARTIFACTS ---
@st.cache_resource
def load_artifacts():
    with open('fraud_detector.pth', 'rb') as f:
        artifacts = pickle.load(f)
    
    model = Autoencoder(artifacts['input_dim'])
    model.load_state_dict(artifacts['model_state'])
    model.eval()
    
    return model, artifacts['scaler_amount'], artifacts['scaler_time'], artifacts['threshold'], artifacts['feature_names']

model, scaler_amount, scaler_time, threshold, feature_names = load_artifacts()

# --- 3. PDF GENERATOR FUNCTION ---
def create_pdf_report(total_tx, fraud_count, money_at_risk):
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Fraud Detection Summary Report", ln=True, align='C')
    pdf.ln(10)
    
    # Stats
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Total Transactions Processed: {total_tx}", ln=True)
    pdf.cell(0, 10, f"Total Fraudulent Transactions Detected: {fraud_count}", ln=True)
    
    percentage = (fraud_count / total_tx) * 100
    pdf.cell(0, 10, f"Fraud Rate: {percentage:.2f}%", ln=True)
    pdf.ln(5)
    
    # Financial Impact
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(194, 24, 7) # Red color
    pdf.cell(0, 10, f"Total Money at Risk: ${money_at_risk:,.2f}", ln=True)
    
    # Disclaimer
    pdf.ln(20)
    pdf.set_text_color(100, 100, 100) # Gray
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, "Note: This report is generated by an AI Autoencoder model. Flagged transactions should be verified manually by a fraud analyst.")
    
    return pdf.output(dest='S').encode('latin-1')

# --- 4. UI LAYOUT ---
st.title("🛡️ Credit Card Fraud Detector")
st.write("Based on Autoencoder Anomaly Detection")

tab1, tab2 = st.tabs(["📝 Single Transaction", "📂 Batch File Upload"])

# TAB 1: SINGLE TRANSACTION (Unchanged)
with tab1:
    st.sidebar.header("Single Transaction Details")
    user_amount = st.sidebar.number_input("Transaction Amount ($)", min_value=0.0, value=100.0)
    user_time = st.sidebar.number_input("Time (Seconds since start)", min_value=0, value=3600)
    scenario = st.sidebar.selectbox("Simulate Scenario", ["Normal Transaction", "Fraudulent Transaction"])

    if st.button("Analyze Single Transaction"):
        input_data = np.zeros(30)
        if scenario == "Normal Transaction":
            input_data[0:28] = np.random.normal(0, 1.0, 28)
        else:
            input_data[0:28] = np.random.normal(0, 1.0, 28)
            indices = np.random.choice(range(28), 3, replace=False)
            input_data[indices] += np.random.uniform(10, 20, 3) * np.random.choice([-1, 1], 3)

        scaled_amt = scaler_amount.transform([[user_amount]])
        scaled_tm = scaler_time.transform([[user_time]])
        input_data[28] = scaled_amt[0][0]
        input_data[29] = scaled_tm[0][0]
        
        input_tensor = torch.FloatTensor(input_data).unsqueeze(0)
        with torch.no_grad():
            reconstruction = model(input_tensor)
            loss_per_feature = (input_tensor - reconstruction) ** 2
            total_loss = torch.mean(loss_per_feature).item()
        
        col1, col2 = st.columns(2)
        col1.metric("Anomaly Score", f"{total_loss:.4f}")
        col2.metric("Threshold", f"{threshold:.4f}")

        if total_loss > threshold:
            st.error("🚨 FRAUD DETECTED!")
        else:
            st.success("✅ Transaction Normal")

# TAB 2: BATCH PROCESSING (Updated)
with tab2:
    st.header("Upload Transaction Batch")
    uploaded_file = st.file_uploader("Choose a CSV file", type="csv")
    
    if uploaded_file is not None:
        try:
            batch_df = pd.read_csv(uploaded_file)
            st.write(f"Loaded {len(batch_df)} transactions.")
            
            if st.button("Process Batch"):
                with st.spinner("Processing transactions..."):
                    # Preprocessing
                    process_df = batch_df.copy()
                    process_df['scaled_amount'] = scaler_amount.transform(process_df['Amount'].values.reshape(-1, 1))
                    process_df['scaled_time'] = scaler_time.transform(process_df['Time'].values.reshape(-1, 1))
                    
                    feature_cols = [f'V{i}' for i in range(1, 29)] + ['scaled_amount', 'scaled_time']
                    X_input = process_df[feature_cols].values
                    X_tensor = torch.FloatTensor(X_input)
                    
                    # Prediction
                    with torch.no_grad():
                        reconstructions = model(X_tensor)
                        loss = torch.mean((X_tensor - reconstructions) ** 2, dim=1).numpy()
                    
                    # Logic
                    predictions = ['Fraud' if l > threshold else 'Normal' for l in loss]
                    
                    # Calculate Stats for Report
                    process_df['Prediction'] = predictions
                    fraud_df = process_df[process_df['Prediction'] == 'Fraud']
                    
                    total_tx = len(batch_df)
                    fraud_count = len(fraud_df)
                    money_at_risk = fraud_df['Amount'].sum() # Uses original Amount
                    
                    # Create CSV (Row Number, Prediction)
                    results_csv = pd.DataFrame({
                        'Row Number': range(1, total_tx + 1),
                        'Prediction': predictions
                    })
                    
                    # Show Stats on Screen
                    st.divider()
                    c1, c2 = st.columns(2)
                    c1.metric("Total Fraud Found", fraud_count)
                    c2.metric("Money at Risk", f"${money_at_risk:,.2f}")
                    
                    st.subheader("Downloads")
                    d1, d2 = st.columns(2)
                    
                    # Download CSV
                    csv_data = results_csv.to_csv(index=False).encode('utf-8')
                    d1.download_button(
                        label="📄 Download Results (CSV)",
                        data=csv_data,
                        file_name='fraud_results.csv',
                        mime='text/csv',
                    )
                    
                    # Download PDF Report
                    pdf_bytes = create_pdf_report(total_tx, fraud_count, money_at_risk)
                    d2.download_button(
                        label="Vm Download Risk Report (PDF)",
                        data=pdf_bytes,
                        file_name='fraud_report.pdf',
                        mime='application/pdf'
                    )
                        
        except Exception as e:
            st.error(f"Error: {e}")